'use strict';

/**
 * The graphics lineage: struct ABI, SPIR-V reflection, producer synthesis, and the driver
 * round-trip that turns a vertex or fragment shader into carvable microcode.
 *
 * Split into two halves on purpose. The first needs nothing but Python and runs anywhere the
 * rest of the suite does; the second needs an NVIDIA GPU, a Vulkan driver and slangc, and is
 * SKIPPED rather than failed without them - the same bargain `test_endtoend.js` makes.
 *
 * The digests below are not arbitrary. Each was produced by an independent C++ harness built
 * against the real Vulkan headers, and pinning against them is what says the ctypes port did
 * not quietly drift. `e2d27b23`/`f6470592` additionally distinguish a CORRECT descriptor
 * layout from a superset (`0a206c89`) and from a UNIFORM_BUFFER_DYNAMIC substitution
 * (`de06f203`), which were measured to change the generated code.
 *
 *   ELECTRON_RUN_AS_NODE=1 Code.exe tools/test_gfx.js
 */

const cp = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const nvcache = require(path.join(ROOT, 'src', 'nvcache.js'));
const spawn = require(path.join(ROOT, 'src', 'spawn.js'));

const VK_COMPILE = path.join(ROOT, 'src', 'vk_compile.py');
const REFLECT = path.join(ROOT, 'src', 'spirv_reflect.py');
const ABI = path.join(ROOT, 'tools', 'vk_abi.json');
const FIXTURES = path.join(__dirname, 'fixtures', 'gfx');

let checks = 0;
let failures = 0;
let skipped = 0;

function check(condition, what, detail = '') {
  checks++;
  if (condition) return true;
  failures++;
  console.log(`  FAIL  ${what}`);
  if (detail) console.log(`        ${String(detail).split('\n').slice(0, 5).join('\n        ')}`);
  return false;
}

function skip(what) { skipped++; console.log(`  skip  ${what}`); }
function section(title) { console.log(`\n${title}`); }

/**
 * Run a tool the way the extension runs it.
 *
 * `spawn.environment` with the same scrub the compile road applies is the point: without it
 * these measurements were taken under whatever implicit Vulkan layers this machine happens to
 * have - Steam's overlay, RenderDoc, Nsight - while the shipped path forbids exactly those.
 * Digests pinned under conditions production does not use are not evidence about production.
 */
function run(exe, args, env) {
  const r = cp.spawnSync(exe, args, {
    encoding: 'utf8', maxBuffer: 1 << 26,
    env: spawn.environment(env || {}, spawn.VULKAN_ENV)
  });
  return {
    code: r.status,
    stdout: (r.stdout || '').replace(/\r\n/g, '\n'),
    stderr: (r.stderr || '').replace(/\r\n/g, '\n'),
    spawnError: r.error
  };
}

/** The interpreter the extension would use, or null. */
function findPython() {
  for (const exe of process.platform === 'win32' ? ['py', 'python'] : ['python3', 'python']) {
    const r = run(exe, ['--version']);
    if (!r.spawnError && r.code === 0) return exe;
  }
  return null;
}

const PY = findPython();

// Filled in once the async body starts; read by `unready` below.
let probe = null;

/**
 * Why a section cannot run, or null.
 *
 * `fixtures` must list every file the section uses unconditionally - too few and it FAILs
 * where it meant to skip, too many and it skips checks that would have run.
 */
function unready(what, fixtures, { gpu = false } = {}) {
  if (!PY) return 'no Python interpreter';
  const missing = (fixtures || []).filter(f => !fs.existsSync(f));
  if (missing.length) {
    return `no ${what} fixture(s): ${missing.map(f => path.basename(f)).join(', ')}`;
  }
  if (gpu && (!probe || probe.code !== 0)) {
    const said = ((probe && (probe.stderr || probe.stdout)) || '').trim().split('\n')[0];
    return `no usable Vulkan device for the ${what} round-trip${said ? `: ${said}` : ''}`;
  }
  return null;
}

// --------------------------------------------------------------------------- ABI

section('1. The Vulkan struct ABI');

if (!PY) {
  skip('no Python interpreter - the graphics lineage needs one, as the NVRTC backend does');
} else {
  // Not a style check. A field at the wrong offset makes the driver read a plausible value
  // from the wrong place, and the result is a shader compiled to the wrong thing rather than
  // an error - so ctypes' arithmetic is checked against what a C compiler computed from the
  // real headers. The frozen file is regenerated by `tools/vk_abi_freeze.py`.
  const report = run(PY, [VK_COMPILE, '--layout']);
  if (!check(report.code === 0, 'vk_compile.py reports its struct layout', report.stderr)) {
    // nothing to compare against
  } else if (!check(fs.existsSync(ABI), 'the frozen C layout is present', ABI)) {
    // nothing to compare against
  } else {
    const mine = JSON.parse(report.stdout);
    const frozen = JSON.parse(fs.readFileSync(ABI, 'utf8'));
    let mismatches = 0;
    let fields = 0;
    for (const name of Object.keys(frozen)) {
      const got = mine[name];
      if (!got) { mismatches++; console.log(`        missing from ctypes: ${name}`); continue; }
      // Offsets must match exactly; size must be at least the real one. Two structs are
      // declared as a prefix plus a `_tail` reserve on purpose - only their leading fields are
      // ever read, but the driver writes the whole thing, so the allocation has to cover a
      // struct this file does not describe field by field. Over-allocating is the safe
      // direction and under-allocating is the buffer overrun, so the rule is `>=` rather than
      // an exemption list that would stop checking them at all.
      if (got.sizeof < frozen[name].sizeof) {
        mismatches++;
        console.log(`        ${name}: ctypes allocates ${got.sizeof} for a struct C makes ` +
          `${frozen[name].sizeof} - the driver would write past the end`);
      }
      for (const [field, offset] of Object.entries(frozen[name].fields)) {
        fields++;
        if (got.fields[field] !== offset) {
          mismatches++;
          console.log(`        ${name}.${field}: ctypes ${got.fields[field]}, C ${offset}`);
        }
      }
    }
    check(mismatches === 0,
      `every struct agrees with the C compiler ` +
      `(${Object.keys(frozen).length} structs, ${fields} fields)`,
      `${mismatches} mismatch(es)`);
    check(Object.keys(mine).length === Object.keys(frozen).length,
      'and neither side declares a struct the other does not',
      `ctypes ${Object.keys(mine).length}, frozen ${Object.keys(frozen).length}`);
  }
}

// --------------------------------------------------------------------------- reflection

section('2. SPIR-V reflection and producer synthesis');

const haveFixtures = fs.existsSync(path.join(FIXTURES, 'fsMain.spv'));

if (!PY) {
  skip('no Python interpreter');
} else if (!haveFixtures) {
  skip(`no SPIR-V fixtures under ${path.relative(ROOT, FIXTURES)}`);
} else {
  const reflected = run(PY, [REFLECT, path.join(FIXTURES, 'vsMain.spv'),
    path.join(FIXTURES, 'fsMain.spv'), '--json']);
  if (check(reflected.code === 0, 'the fixture pair reflects', reflected.stderr)) {
    const { layout } = JSON.parse(reflected.stdout);
    const tuples = layout.map(d => `${d.set}:${d.binding}:${d.type}:${d.count}`).join(' ');
    // The union of what the two stages declare: UBO 0, sampled image 1, sampler 2, SSBO 3.
    check(tuples === '0:0:6:1 0:1:2:1 0:2:0:1 0:3:7:1',
      'the merged layout is what the two stages actually declare', tuples);
  }

  // A layout no VkDescriptorSetLayout can express must be refused by name. Two descriptors at
  // one (set, binding) is the usual HLSL artefact - `t0` and `s0` collide without -fvk-s-shift.
  const collide = path.join(FIXTURES, 'collide.spv');
  if (fs.existsSync(collide)) {
    const r = run(PY, [REFLECT, collide, '--json']);
    check(r.code !== 0 && /declared twice/.test(r.stderr),
      'an inexpressible layout is refused rather than guessed at', r.stderr.split('\n')[0]);
  }
}

// --------------------------------------------------------------------------- round trip

section('3. The driver round-trip');

const KNOWN = {
  // A descriptor-free pair, and the same pair through the layout fixtures.
  plain: { vs: 'vs.spv', fs: 'fs.spv', layout: [], pixel: '6e77f0dbf9f6', vertex: '888a1deae26e' },
  bound: { vs: 'vsMain.spv', fs: 'fsMain.spv',
    layout: [[0, 0, 6, 1], [0, 1, 2, 1], [0, 2, 0, 1], [0, 3, 7, 1]],
    pixel: 'e2d27b236f6d', vertex: 'f64705929fad' }
};
const WRONG = { superset: '0a206c89ea37', dynamic: 'de06f203bf3b' };

/**
 * The device these digests were recorded on.
 *
 * A pinned digest is a fact about one compiler compiling for one architecture. On any other
 * NVIDIA GPU the ISA itself differs, so every pin below would FAIL - reporting "the ctypes port
 * drifted" on a machine where nothing had drifted, and drowning the checks that ARE
 * machine-independent (a generated hull equals the real one, dropping the any-hit shader
 * changes nothing else - those compare two runs on whatever machine is running them).
 *
 * So the pins are gated and SKIPPED elsewhere, and the gate names what to do: re-record them
 * here, the way `tools/vk_abi_freeze.py` re-records the struct ABI.
 */
const PINNED_DEVICE = /NVIDIA RTX A4500/i;
let pinsApply = false;

/**
 * Pins whose INPUT changed, and which therefore describe a compile that can no longer happen.
 *
 * A digest is a fact about one compiler compiling one module for one architecture. Four of the
 * `.spv` fixtures were regenerated - gsMain, tessHs, msMain and tessGenHs - because the SPIR-V
 * committed with them carried an `ArrayStride` decoration on a `Function`-storage array, which
 * the SDK that produced them accepted and the current one rejects. The shaders did not change;
 * their compiled form did.
 *
 * So these pins are not merely device-specific any more, they are stale: on an A4500 they would
 * now FAIL, and the failure would read as a driver or compiler regression when nothing about
 * either changed. Skipping them on every machine, with the reason, is the honest state until
 * someone re-records them on an A4500 against the new fixtures. Deleting them would throw away
 * the only record of what those pipelines used to produce.
 */
const STALE_PINS = 'the .spv fixture behind it was regenerated under Vulkan SDK 1.4.341.1; ' +
  're-record on an RTX A4500 against the new fixtures';

/**
 * Assert a recorded digest, or skip where this machine cannot be held to it.
 *
 * @param {string} [stale]  why this pin no longer describes a reachable compile. Skips
 *   unconditionally, including on the device it was recorded on - which is the point: that is
 *   the machine where it would otherwise fail for the wrong reason.
 */
function pinned(actual, expected, what, detail, stale) {
  if (stale) return skip(`${what} (${stale})`);
  if (!pinsApply) return skip(`${what} (recorded on an RTX A4500; this is another device)`);
  return check(actual === expected, what, detail || `got ${actual}, want ${expected}`);
}

async function pipeline(tag, request) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nvisa-gfx-'));
  // `finally`, not a call on each exit path. There were three exits and two of them removed
  // the directory; the third was a throw from the carve - a truncated .bin, a file the driver
  // still holds - which leaked the directory AND took the whole suite down with a stack trace
  // instead of one failed check.
  try {
    const cache = path.join(dir, 'cache');
    fs.mkdirSync(cache);
    const file = path.join(dir, 'request.json');
    fs.writeFileSync(file, JSON.stringify(request), 'utf8');

    const r = run(PY, [VK_COMPILE, file], {
      __GL_SHADER_DISK_CACHE_PATH: cache,
      __GL_SHADER_DISK_CACHE: '1',
      __GL_SHADER_DISK_CACHE_SKIP_CLEANUP: '1'
    });
    if (r.code !== 0) {
      return { error: (r.stderr || r.stdout).trim().split('\n')[0], code: r.code };
    }

    const bin = findBin(cache);
    if (!bin) return { error: 'the driver wrote nothing to the isolated cache' };

    let toc = null;
    try { toc = fs.readFileSync(bin.slice(0, -4) + '.toc'); } catch (e) { toc = null; }
    const { objects } = await nvcache.enumerateObjects(fs.readFileSync(bin), {
      source: bin, backend: 'vk', toc, keepMicrocode: true, minCode: 0
    });
    // One stage does not always mean one object. A raytracing shader that calls TraceRay is
    // split at the trace point into separately scheduled pieces, so its stage arrives carrying
    // two of them; the digests are joined in the order the container lists them, which keeps a
    // stage a single string to pin while still showing that it came apart.
    const parts = {};
    for (const o of objects) {
      const stage = (o.metadata && o.metadata.stage) || `code${o.metadata && o.metadata.stageCode}`;
      (parts[stage] = parts[stage] || []).push(o.sha1.slice(0, 12));
    }
    const out = {};
    for (const [stage, digests] of Object.entries(parts)) out[stage] = digests.join('+');
    return out;
  } catch (e) {
    return { error: `carving what the driver wrote failed: ${e.message}` };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

/**
 * Like `pipeline`, but keeping the objects and the cache file rather than digests.
 *
 * The browsing path reads these records; the compile path rebuilds its own from the microcode,
 * so it cannot speak for what the tree and the re-carve actually receive.
 */
async function carve(request) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nvisa-carve-'));
  const cache = path.join(dir, 'cache');
  fs.mkdirSync(cache);
  const file = path.join(dir, 'request.json');
  fs.writeFileSync(file, JSON.stringify(request), 'utf8');
  const r = run(PY, [VK_COMPILE, file], {
    __GL_SHADER_DISK_CACHE_PATH: cache,
    __GL_SHADER_DISK_CACHE: '1',
    __GL_SHADER_DISK_CACHE_SKIP_CLEANUP: '1'
  });
  if (r.code !== 0) {
    fs.rmSync(dir, { recursive: true, force: true });
    return { error: (r.stderr || r.stdout).trim().split('\n')[0] };
  }
  const bin = findBin(cache);
  if (!bin) {
    fs.rmSync(dir, { recursive: true, force: true });
    return { error: 'the driver wrote nothing to the isolated cache' };
  }
  // The bytes come back, not the path: the caller re-carves out of the buffer, so the
  // directory can go now rather than outliving the run.
  let toc = null;
  try { toc = fs.readFileSync(bin.slice(0, -4) + '.toc'); } catch (e) { toc = null; }
  const buf = fs.readFileSync(bin);
  try {
    const { objects } = await nvcache.enumerateObjects(buf, {
      source: bin, backend: 'vk', toc, keepMicrocode: false, minCode: 0
    });
    return { objects, buf, bin };
  } catch (e) {
    return { error: `carving what the driver wrote failed: ${e.message}` };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function findBin(dir) {
  const stack = [dir];
  while (stack.length) {
    const at = stack.pop();
    for (const e of fs.readdirSync(at, { withFileTypes: true })) {
      const full = path.join(at, e.name);
      if (e.isDirectory()) stack.push(full);
      else if (e.name.endsWith('.bin')) return full;
    }
  }
  return null;
}

(async () => {
  probe = PY ? run(PY, [VK_COMPILE, '--probe']) : null;

  if (!PY) {
    skip('no Python interpreter');
  } else if (!haveFixtures) {
    skip(`no SPIR-V fixtures under ${path.relative(ROOT, FIXTURES)}`);
  } else if (!probe || probe.code !== 0) {
    // No NVIDIA device, no Vulkan ICD, a Remote Desktop session: all real, none a defect here.
    skip(`no usable Vulkan device: ${(probe && (probe.stderr || probe.stdout) || '').trim().split('\n')[0]}`);
  } else {
    check(/vendor 0x10DE/i.test(probe.stdout), 'the probe names an NVIDIA device',
      probe.stdout.trim().split('\n').join(' | '));

    // Whether the recorded digests speak for this machine at all.
    pinsApply = PINNED_DEVICE.test(probe.stdout);
    if (!pinsApply) {
      console.log('  note  digests were recorded on an RTX A4500; the pins below are skipped ' +
        'and the relational checks still run');
    }

    for (const [tag, want] of Object.entries(KNOWN)) {
      const got = await pipeline(tag, {
        vs: path.join(FIXTURES, want.vs),
        fs: path.join(FIXTURES, want.fs),
        layout: { bindings: want.layout }
      });
      if (!check(!got.error, `${tag}: the pipeline is created and the driver writes a cache`,
        got.error)) continue;
      pinned(got.pixel, want.pixel,
        `${tag}: the fragment microcode is what the C++ harness produced`,
        `got ${got.pixel}, want ${want.pixel}`);
      pinned(got.vertex, want.vertex,
        `${tag}: the vertex microcode is what the C++ harness produced`,
        `got ${got.vertex}, want ${want.vertex}`);
    }

    // The layout has to be load-bearing, or reproducing it proves nothing.
    const superset = await pipeline('superset', {
      vs: path.join(FIXTURES, 'vsMain.spv'), fs: path.join(FIXTURES, 'fsMain.spv'),
      layout: { bindings: [[0, 0, 6, 1], [0, 1, 2, 1], [0, 2, 0, 1], [0, 3, 7, 1],
        [0, 9, 6, 1], [0, 10, 7, 1], [0, 11, 2, 4]] }
    });
    check(!superset.error, 'a superset layout still builds a pipeline', superset.error);
    pinned(superset.pixel, WRONG.superset,
      'a superset layout still produces the superset code, so the layout is load-bearing',
      superset.error || `got ${superset.pixel}, want ${WRONG.superset}`);

    // A mismatched producer/consumer pair is undefined, and the driver compiles it anyway.
    // Refusing is the only thing standing between that and a listing nobody can tell is wrong.
    const mismatched = await pipeline('mismatch', {
      vs: path.join(FIXTURES, 'vsMain.spv'), fs: path.join(FIXTURES, 'fs.spv'),
      layout: { bindings: [] }
    });
    check(!!mismatched.error && mismatched.code === 1,
      'a producer that does not match the consumer is refused before the driver sees it',
      mismatched.error || `it was accepted: ${JSON.stringify(mismatched)}`);
  }

  // ------------------------------------------------------------------ geometry

  section('4. The geometry stage');

  const gs = path.join(FIXTURES, 'gsMain.spv');
  const whyGeometry = unready('geometry', [gs]);
  if (whyGeometry) {
    skip(whyGeometry);
  } else {
    // The topology is not a free choice: a geometry shader declares the primitive it consumes
    // and the input assembler has to be set to feed it that one. Read from the module, never
    // defaulted - a triangle-input shader behind a point list is a pipeline the driver rejects.
    const r = run(PY, [REFLECT, gs, '--json']);
    if (check(r.code === 0, 'a geometry module reflects', r.stderr)) {
      const m = JSON.parse(r.stdout).modules[0];
      check(m.primitive && m.primitive.topology === 'triangle_list',
        'its declared input primitive gives the topology that must feed it',
        JSON.stringify(m.primitive));
      // Every non-builtin input of a geometry shader is an array indexed by vertex. A producer
      // has to emit the ELEMENT once, so the array dimension comes off before matching.
      check(m.inputs.some(v => v.type.includes('[')),
        'its raw inputs are per-vertex arrays', JSON.stringify(m.inputs));
      check((m.perVertexInputs || []).every(v => !v.type.includes('[')),
        'and the per-vertex view strips the array a producer could not declare',
        JSON.stringify(m.perVertexInputs));
    }

    const noDevice = unready('geometry', [], { gpu: true });
    if (noDevice) {
      skip(noDevice);
    } else {
      // Stage code 4. Established by construction rather than inferred: a pipeline holding
      // exactly one vertex and one geometry module deposits exactly two objects, and one of
      // them is the already-known code 1.
      const paired = await pipeline('geometry', {
        vs: path.join(FIXTURES, 'gsProducer.spv'), gs, fs: null,
        layout: { bindings: [] }, state: { topology: 'triangle_list' }
      });
      if (check(!paired.error, 'a vertex + geometry pipeline is created', paired.error)) {
        pinned(paired.geometry, 'ce4a65b17741',
          'the geometry microcode is what was recorded',
          `got ${paired.geometry}, want ce4a65b17741`, STALE_PINS);
        check(!!paired.vertex, 'and the vertex stage is carved beside it, told apart by code',
          JSON.stringify(paired));
      }

      // A geometry shader needs a producer but does not depend on it, exactly as a fragment
      // shader does not depend on its own. Measured, not assumed: the same shader behind a
      // generated producer must be byte-identical to one behind a hand-written one.
      const generated = path.join(FIXTURES, 'gsGenerated.spv');
      if (fs.existsSync(generated)) {
        const synth = await pipeline('geometry-generated', {
          vs: generated, gs, fs: null,
          layout: { bindings: [] }, state: { topology: 'triangle_list' }
        });
        check(!synth.error && synth.geometry === paired.geometry,
          'and a generated producer yields the same geometry microcode as the real one',
          synth.error || `generated ${synth.geometry}, real ${paired.geometry}`);
      }

      // The wrong topology is the failure this stage makes possible, and the driver does NOT
      // object to it - measured: it creates the pipeline, exits zero, and returns the same
      // microcode. The same shape of silence as a mismatched varying interface, so it is
      // refused here for the same reason.
      const wrong = await pipeline('geometry-wrong-topology', {
        vs: path.join(FIXTURES, 'gsProducer.spv'), gs, fs: null,
        layout: { bindings: [] }, state: { topology: 'point_list' }
      });
      check(!!wrong.error && wrong.code === 1,
        'a topology the geometry shader does not consume is refused before the driver sees it',
        wrong.error || `it was accepted: ${JSON.stringify(wrong)}`);
    }
  }

  // ------------------------------------------------------------------ tessellation

  section('5. The tessellation stages');

  const hs = path.join(FIXTURES, 'tessHs.spv');
  const ds = path.join(FIXTURES, 'tessDs.spv');
  const whyTessellation = unready('tessellation', [hs, ds]);
  if (whyTessellation) {
    skip(whyTessellation);
  } else {
    // The generated half has to be VALID for every domain, not just the one the fixtures use.
    // gl_TessLevelOuter is float[4] and gl_TessLevelInner is float[2] in SPIR-V whatever the
    // domain is, so a triangle domain's `float edges[3]` became an OpStore of the wrong-sized
    // array - rejected by spirv-val, built anyway by this driver, and invisible because the
    // fixtures are quads whose 4 and 2 already matched.
    const genCheck = run(PY, [REFLECT, ds, '--counterpart',
      path.join(os.tmpdir(), 'nvisa-gen-hull.slang')]);
    if (check(genCheck.code === 0, 'a counterpart hull is generated', genCheck.stderr)) {
      const text = fs.readFileSync(path.join(os.tmpdir(), 'nvisa-gen-hull.slang'), 'utf8');
      check(/float edges\[4\] : SV_TessFactor;/.test(text),
        'with its outer factors sized to the builtin, not to the domain');
      check(/float inside\[2\] : SV_InsideTessFactor;/.test(text),
        'and its inner factors likewise');
      check(/c\.edges\[3\] = /.test(text) && /c\.inside\[1\] = /.test(text),
        'and every element written, so none of the array is left undefined');
      // `outputtopology` names a WINDING in Slang, not an output primitive - the spelling that
      // looks right for isolines, `line`, lowers to a mesh-shader execution mode and makes the
      // module invalid. Measured; see the comment on the emission.
      check(/\[outputtopology\("triangle_(cw|ccw)"\)\]/.test(text),
        'and a winding spelling even where the domain draws no triangles');
      fs.rmSync(path.join(os.tmpdir(), 'nvisa-gen-hull.slang'), { force: true });
    }

    // A hull shader carries the whole declaration - domain, spacing, winding, how many control
    // points it emits. A domain shader carries only the domain, because in HLSL the rest is
    // the hull shader's to state. That asymmetry is why the two synthesis directions differ.
    const rh = run(PY, [REFLECT, hs, '--json']);
    if (check(rh.code === 0, 'a hull module reflects', rh.stderr)) {
      const m = JSON.parse(rh.stdout).modules[0];
      check(m.tessellation && m.tessellation.domain === 'quads' &&
        m.tessellation.spacing === 'fractional_odd' && m.tessellation.outputVertices === 4,
        'with its domain, spacing and control-point count', JSON.stringify(m.tessellation));
      check(m.patchControlPoints === 4,
        'and the patch size, taken from its input array length', String(m.patchControlPoints));
    }
    const rd = run(PY, [REFLECT, ds, '--json']);
    if (check(rd.code === 0, 'a domain module reflects', rd.stderr)) {
      const m = JSON.parse(rd.stdout).modules[0];
      check(m.tessellation && m.tessellation.domain === 'quads' &&
        m.tessellation.spacing === null,
        'carrying its domain but not the spacing, which is the hull shader\'s to declare',
        JSON.stringify(m.tessellation));
    }

    const noDevice = unready('tessellation', [], { gpu: true });
    if (noDevice) {
      skip(noDevice);
    } else {
      const trio = {
        vs: path.join(FIXTURES, 'tessVs.spv'), fs: null, hs, ds,
        layout: { bindings: [] },
        state: { topology: 'patch_list', patchControlPoints: 4 }
      };
      const real = await pipeline('tess', trio);
      if (check(!real.error, 'a vertex + hull + domain pipeline is created', real.error)) {
        pinned(real.hull, '618d558286e5', 'the hull microcode is what was recorded',
          `got ${real.hull}, want 618d558286e5`, STALE_PINS);
        pinned(real.domain, '22d5ea41c851', 'the domain microcode is what was recorded',
          `got ${real.domain}, want 22d5ea41c851`, STALE_PINS);
      }

      // The two synthesis directions are NOT equally safe, and the difference is measured
      // rather than assumed. A generated hull leaves the domain shader untouched. A generated
      // domain reads every output the hull declares, where a real one may read fewer - so the
      // driver eliminates less and the hull comes out larger. That makes the second an upper
      // bound, which the compile path reports as one.
      const genHs = path.join(FIXTURES, 'tessGenHs.spv');
      if (fs.existsSync(genHs)) {
        // Compiling a DOMAIN shader: the hull is the one being generated, and the stage under
        // test comes out unchanged.
        const synth = await pipeline('tess-gen-hs', { ...trio, hs: genHs });
        check(!synth.error && synth.domain === real.domain,
          'compiling a domain shader against a GENERATED hull leaves it byte-identical',
          synth.error || `got ${synth.domain}, want ${real.domain}`);
      }
      const genDs = path.join(FIXTURES, 'tessGenDs.spv');
      if (fs.existsSync(genDs)) {
        // Compiling a HULL shader: the domain is generated, and it reads every output the
        // hull declares where the real one reads fewer - so less is eliminated and the hull
        // comes out larger. An upper bound, which the compile path reports as one.
        const synth = await pipeline('tess-gen-ds', { ...trio, ds: genDs });
        check(!synth.error && synth.hull !== real.hull,
          'compiling a hull shader against a GENERATED domain does NOT, which is why that ' +
          'case is reported as an upper bound',
          synth.error || `both ${synth.hull}`);
      }

      // A tessellation pipeline with no patch size is not a pipeline. There is no default
      // worth guessing: it is the hull shader's input array length.
      const noPatch = await pipeline('tess-no-patch', {
        ...trio, state: { topology: 'patch_list' }
      });
      check(!!noPatch.error && /patchControlPoints/.test(noPatch.error),
        'a tessellation pipeline with no patch size is refused by name',
        noPatch.error || 'it was accepted');
    }
  }

  // ------------------------------------------------------------------ mesh

  section('6. The mesh and amplification stages');

  const ms = path.join(FIXTURES, 'msMain.spv');
  const as = path.join(FIXTURES, 'asMain.spv');
  const whyMesh = unready('mesh', [ms], { gpu: true });
  if (whyMesh) {
    skip(whyMesh);
  } else {
    // A mesh pipeline has no vertex stage at all - the mesh shader IS the front of it - so
    // this is the one graphics pipeline built with no vertex input and no input assembler.
    const alone = await pipeline('mesh', { ms, fs: null, layout: { bindings: [] } });
    if (check(!alone.error, 'a mesh shader alone makes a pipeline', alone.error)) {
      // Stage code 9, established by construction: this pipeline holds exactly one module.
      pinned(alone.mesh, '79fc9202f25d', 'the mesh microcode is what was recorded',
        `got ${alone.mesh}, want 79fc9202f25d`, STALE_PINS);
    }

    if (fs.existsSync(as)) {
      const both = await pipeline('mesh-amp', { ms, ts: as, fs: null, layout: { bindings: [] } });
      if (check(!both.error, 'an amplification shader dispatches it', both.error)) {
        // ...and code 10 is what the second object is, since only the task stage was added.
        check(!!both.amplification, 'depositing an amplification object beside the mesh one',
          JSON.stringify(both));
        // The mesh shader reads a payload the task shader supplies, so it is NOT the same
        // shader in the two pipelines. Mesh depends on its producer the way every consuming
        // stage does.
        check(both.mesh !== alone.mesh,
          'and the mesh half differs, because the payload it reads now has a source',
          `both ${both.mesh}`);
      }
      // A task shader with nothing to dispatch is not a pipeline.
      const orphan = await pipeline('amp-alone', { ts: as, fs: null, layout: { bindings: [] } });
      check(!!orphan.error && /mesh/.test(orphan.error),
        'an amplification shader with no mesh shader is refused by name',
        orphan.error || 'it was accepted');
    }
  }

  // ------------------------------------------------------------------ ray query

  section('7. Inline ray tracing');

  // Ray query needs no raytracing pipeline: it lives inside an ordinary shader, so the
  // existing graphics path reaches it. What it does need is the features and extensions the
  // modules declare - and without them the driver builds the pipeline anyway and returns 408
  // instructions of plausible SASS. Nine validation errors, none of them visible in the
  // output. That is why the capabilities are read from the SPIR-V rather than hardcoded.
  const rqFs = path.join(FIXTURES, 'rqFs.spv');
  const whyQuery = unready('ray-query', [rqFs]);
  if (whyQuery) {
    skip(whyQuery);
  } else {
    const r = run(PY, [REFLECT, rqFs, '--json']);
    if (check(r.code === 0, 'a ray-query module reflects', r.stderr)) {
      const m = JSON.parse(r.stdout).modules[0];
      check((m.capabilities || []).includes(4479),
        'declaring the RayQueryKHR capability the device has to be told about',
        JSON.stringify(m.capabilities));
      check((m.extensions || []).includes('SPV_KHR_ray_query'),
        'and the SPIR-V extension that goes with it', JSON.stringify(m.extensions));
      check(m.descriptors.some(d => d.type === 1000150000),
        'with the acceleration structure reflected as an ordinary descriptor',
        JSON.stringify(m.descriptors.map(d => d.type)));
    }

    const noDevice = unready('ray-query', [], { gpu: true });
    if (noDevice) {
      skip(noDevice);
    } else {
      const got = await pipeline('rayquery', {
        vs: path.join(FIXTURES, 'rqVs.spv'), fs: rqFs,
        layout: { bindings: [[0, 0, 1000150000, 1], [0, 1, 6, 1]] }, validate: true
      });
      // `validate: true` is the point of this one: it passed WITHOUT the features before, and
      // the only thing that said otherwise was the layer.
      check(!got.error, 'a ray-query pipeline is valid once its capabilities are enabled',
        got.error);
      pinned(got.pixel, 'b0d9cfaca1c4', 'and the fragment microcode is what was recorded');
    }
  }

  // ------------------------------------------------------------------ raytracing

  section('8. The raytracing stages');

  // The other end of ray tracing from section 7. A ray query lives inside an ordinary shader
  // and needs no pipeline of its own; these six stages ARE the pipeline, and none of them can
  // be compiled alone. The raygeneration shader is the only one the driver will start, and the
  // rest are reachable only through the shader groups built around it.
  const rtFiles = ['rtRgen', 'rtMiss', 'rtChit', 'rtAhit', 'rtSect', 'rtCall']
    .map(n => path.join(FIXTURES, `${n}.spv`));
  const [RGEN, MISS, CHIT, AHIT, SECT, CALL] = rtFiles;
  const rtLayout = { bindings: [[0, 0, 1000150000, 1], [0, 1, 3, 1], [0, 2, 6, 1]] };

  const whyRt = unready('raytracing', rtFiles);
  if (whyRt) {
    skip(whyRt);
  } else {
    const r = run(PY, [REFLECT, RGEN, '--json']);
    if (check(r.code === 0, 'a raygeneration module reflects', r.stderr)) {
      const m = JSON.parse(r.stdout).modules[0];
      // 4479 is RayTracingKHR and 4472 is RayQueryKHR. They were the wrong way round here for
      // a while and nothing caught it, because the ray-query fixture of section 7 declares
      // both - so the wrong constant still named a capability that module had. This fixture
      // declares only the raytracing one, which is what makes the mix-up visible.
      check((m.capabilities || []).includes(4479),
        'declaring RayTracingKHR and not RayQueryKHR', JSON.stringify(m.capabilities));
      check(!(m.capabilities || []).includes(4472),
        'which is the pair that was once swapped', JSON.stringify(m.capabilities));
      check((m.entryPoints || []).some(e => e.stage === 'raygeneration'),
        'and reporting its execution model', JSON.stringify(m.entryPoints));
      check((m.extensions || []).includes('SPV_KHR_ray_tracing'),
        'with the SPIR-V extension that goes with it', JSON.stringify(m.extensions));
    }

    const noDevice = unready('raytracing', [], { gpu: true });
    if (noDevice) {
      skip(noDevice);
    } else {
      const full = await pipeline('rt-full', {
        rgen: RGEN, miss: MISS, chit: CHIT, ahit: AHIT, sect: SECT, call: CALL,
        layout: rtLayout, validate: true
      });
      if (check(!full.error, 'all six raytracing stages build one valid pipeline', full.error)) {
        for (const stage of ['raygeneration', 'miss', 'closesthit', 'anyhit',
          'intersection', 'callable']) {
          check(!!full[stage], `and the ${stage} shader comes back out of the cache`,
            JSON.stringify(Object.keys(full)));
        }
        // Two digests joined by '+' is one stage that compiled to two objects. A shader that
        // calls TraceRay is split at the trace point, because the trace suspends it: the code
        // after the call is scheduled separately and resumed when the ray is answered.
        check((full.raygeneration || '').includes('+'),
          'the raygeneration shader comes apart at its TraceRay call', full.raygeneration);
        check((full.closesthit || '').includes('+'),
          'and the closest-hit shader at its CallShader call', full.closesthit);
        pinned(`${full.raygeneration} ${full.miss} ${full.intersection}`,
          '9eeec1ef5ed0+4f255e6a3d6c 7f95ed9babd6 c7a82af21201',
          'and the microcode is what was recorded');
      }

      // What the BROWSER needs from these objects, which is not what the compile road needs.
      // The compile road rebuilds every record itself, so it never noticed that raytracing
      // objects were missing the fields the tree reads - and the tree dereferences them
      // without asking, so one raytracing payload in a cache broke the whole view.
      const carved = await carve({
        rgen: RGEN, miss: MISS, chit: CHIT, ahit: AHIT, sect: SECT, call: CALL,
        layout: rtLayout
      });
      if (check(!carved.error, 'a raytracing cache enumerates', carved.error)) {
        check(carved.objects.every(o => Number.isInteger(o.instructions) && o.instructions > 0),
          'every raytracing object carries an instruction count',
          JSON.stringify(carved.objects.map(o => [o.name, o.instructions])));
        check(carved.objects.every(o => o.sha1 && o.metadata && o.metadata.stage),
          'and its identity and stage');

        // The driver compiles each shader twice and writes both copies; one entry point means
        // one object. Keyed per object rather than per file - when this was decided per file,
        // a single raytracing payload put every NVuc object in a mixed cache through the same
        // rule, and unnamed ones (all sharing the key `null`) silently collapsed into one.
        const names = carved.objects.map(o => o.name);
        check(new Set(names).size === names.length,
          'and each entry point appears exactly once', names.join(' '));

        // Re-carving is what the browser does when the object is clicked, having dropped the
        // microcode. Several raytracing entry points share one frame offset, so the offset
        // alone cannot pick one - it used to return null and the user was told, wrongly, that
        // the cache file had changed underneath them.
        let recarved = 0;
        for (const o of carved.objects) {
          const again = nvcache.carveAt(carved.buf, o.offset,
            { source: carved.bin, backend: 'vk', name: o.name });
          if (again && again.name === o.name && again.sha1 === o.sha1) recarved++;
        }
        check(recarved === carved.objects.length,
          'and can be carved again one entry point at a time',
          `${recarved} of ${carved.objects.length}`);
      }

      // What moves what, measured rather than assumed - the same question section 3 asked of
      // render state. A raytracing pipeline is compiled as a whole, so membership of it is the
      // thing that might reach into a shader.
      const noAhit = await pipeline('rt-no-ahit', {
        rgen: RGEN, miss: MISS, chit: CHIT, sect: SECT, call: CALL,
        layout: rtLayout, validate: true
      });
      check(!noAhit.error && noAhit.raygeneration === full.raygeneration &&
            noAhit.closesthit === full.closesthit && noAhit.miss === full.miss,
        'dropping the any-hit shader leaves every other stage byte-identical',
        noAhit.error || `chit ${noAhit.closesthit} vs ${full.closesthit}`);

      // The closest-hit shader calls CallShader. Take the callable shader out of the pipeline
      // and that call has nothing to reach, so the shader holding it is compiled differently -
      // and nothing else is.
      const noCall = await pipeline('rt-no-call', {
        rgen: RGEN, miss: MISS, chit: CHIT, ahit: AHIT, sect: SECT,
        layout: rtLayout, validate: true
      });
      check(!noCall.error && noCall.closesthit !== full.closesthit,
        'dropping the callable shader moves the shader that calls it',
        noCall.error || `${noCall.closesthit} vs ${full.closesthit}`);
      check(!noCall.error && noCall.raygeneration === full.raygeneration &&
            noCall.miss === full.miss && noCall.intersection === full.intersection,
        'and moves nothing else', noCall.error);

      // Membership narrows towards the caller, not away from it: the miss shader is reached
      // from the raygeneration shader's TraceRay and does not change it, while the hit group -
      // which that same TraceRay may resume into - does.
      const alone = await pipeline('rt-rgen', { rgen: RGEN, layout: rtLayout, validate: true });
      const withMiss = await pipeline('rt-rgen-miss', {
        rgen: RGEN, miss: MISS, layout: rtLayout, validate: true
      });
      check(!alone.error && !withMiss.error && alone.raygeneration === withMiss.raygeneration,
        'adding a miss shader does not change the raygeneration shader',
        alone.error || withMiss.error || `${alone.raygeneration} vs ${withMiss.raygeneration}`);
      check(!alone.error && alone.raygeneration !== full.raygeneration,
        'but adding a hit group does', `${alone.raygeneration} vs ${full.raygeneration}`);

      // The two requests that are not pipelines at all.
      const mixed = await pipeline('rt-mixed', {
        rgen: RGEN, vs: path.join(FIXTURES, 'vs.spv'), layout: rtLayout
      });
      check(mixed.error && mixed.code === 2 && /different kinds of pipeline/.test(mixed.error),
        'a request mixing raytracing and graphics stages is refused', mixed.error);
      const orphan = await pipeline('rt-orphan', { chit: CHIT, layout: rtLayout });
      check(orphan.error && orphan.code === 2 && /raygeneration/.test(orphan.error),
        'and so is a hit shader with no raygeneration shader to launch it', orphan.error);
    }
  }

  // ------------------------------------------------------------------ validation

  section('9. What the validation layer makes of these pipelines');

  // The check that would have found the bug that hid the longest. `dynamicRendering` was
  // never enabled - the 1.3 features struct carried the sType of the 1.1 one - and every
  // pipeline was built with `renderPass = NULL` on a device that had not asked for it. The
  // microcode still matched a C++ harness byte for byte, because this driver permits it. No
  // digest, no ABI diff and no exit code could see that. The layer saw it immediately.
  //
  // Skipped, not failed, where the layer is absent: it ships with the Vulkan SDK rather than
  // with the display driver, so a machine that compiles shaders perfectly well may not have it.
  if (!PY || !haveFixtures) {
    skip('no Python interpreter or no fixtures');
  } else if (!probe || probe.code !== 0) {
    skip('no usable Vulkan device');
  } else {
    const cases = [
      { tag: 'fragment', request: { vs: path.join(FIXTURES, 'vs.spv'),
        fs: path.join(FIXTURES, 'fs.spv'), layout: { bindings: [] } } },
      { tag: 'descriptors', request: { vs: path.join(FIXTURES, 'vsMain.spv'),
        fs: path.join(FIXTURES, 'fsMain.spv'),
        layout: { bindings: [[0, 0, 6, 1], [0, 1, 2, 1], [0, 2, 0, 1], [0, 3, 7, 1]] } } },
      { tag: 'vertex only', request: { vs: path.join(FIXTURES, 'vs.spv'), fs: null,
        layout: { bindings: [] } } },
      { tag: 'geometry', request: { vs: path.join(FIXTURES, 'gsProducer.spv'),
        fs: null, gs: path.join(FIXTURES, 'gsMain.spv'),
        layout: { bindings: [] }, state: { topology: 'triangle_list' } } },
      { tag: 'tessellation', request: { vs: path.join(FIXTURES, 'tessVs.spv'), fs: null,
        hs: path.join(FIXTURES, 'tessHs.spv'), ds: path.join(FIXTURES, 'tessDs.spv'),
        layout: { bindings: [] },
        state: { topology: 'patch_list', patchControlPoints: 4 } } },
      { tag: 'mesh', request: { ms: path.join(FIXTURES, 'msMain.spv'),
        ts: path.join(FIXTURES, 'asMain.spv'), fs: null, layout: { bindings: [] } } },
      { tag: 'ray query', request: { vs: path.join(FIXTURES, 'rqVs.spv'),
        fs: path.join(FIXTURES, 'rqFs.spv'),
        layout: { bindings: [[0, 0, 1000150000, 1], [0, 1, 6, 1]] } } },
      // Not a graphics pipeline at all, and it is here for that reason: it goes through a
      // different creation call, with none of the state the others carry, so nothing the
      // layer says about the ones above is evidence about this one.
      { tag: 'raytracing', request: { rgen: path.join(FIXTURES, 'rtRgen.spv'),
        miss: path.join(FIXTURES, 'rtMiss.spv'), chit: path.join(FIXTURES, 'rtChit.spv'),
        ahit: path.join(FIXTURES, 'rtAhit.spv'), sect: path.join(FIXTURES, 'rtSect.spv'),
        call: path.join(FIXTURES, 'rtCall.spv'),
        layout: { bindings: [[0, 0, 1000150000, 1], [0, 1, 3, 1], [0, 2, 6, 1]] } } }
    ].filter(c => Object.values(c.request)
      .every(v => typeof v !== 'string' || fs.existsSync(v)));

    let unavailable = false;
    for (const c of cases) {
      const got = await pipeline(`validate-${c.tag}`, { ...c.request, validate: true });
      if (got.error && /not installed/.test(got.error)) { unavailable = true; break; }
      // Exit 5 is the layer's verdict specifically, and its message carries the VUID - which
      // is the only part that says what to change.
      check(!got.error, `${c.tag}: builds a pipeline the validation layer accepts`, got.error);
    }
    if (unavailable) {
      skip('VK_LAYER_KHRONOS_validation is not installed (it ships with the Vulkan SDK)');
    }
  }

  console.log(`\n${failures ? 'FAIL' : 'PASS'}  ${checks} checks, ${failures} failures, ` +
    `${skipped} skipped`);
  process.exit(failures ? 1 : 0);
})().catch(e => { console.log(`\nFAIL  ${e && e.stack ? e.stack : e}`); process.exit(1); });
