'use strict';

/**
 * The graphics lineage: struct ABI, SPIR-V reflection, producer synthesis, and the driver
 * round-trip that turns a vertex or fragment shader into carvable microcode.
 *
 * Split into two halves on purpose. The first needs nothing but Python and runs anywhere the
 * rest of the suite does; the second needs an NVIDIA GPU, a Vulkan driver and slangc, and is
 * SKIPPED rather than failed without them - the same bargain `test_endtoend.js` makes.
 *
 * The digests below are not arbitrary. Each was produced by an independent C++ harness built
 * against the real Vulkan headers, and pinning against them is what says the ctypes port did
 * not quietly drift. `e2d27b23`/`f6470592` additionally distinguish a CORRECT descriptor
 * layout from a superset (`0a206c89`) and from a UNIFORM_BUFFER_DYNAMIC substitution
 * (`de06f203`), which were measured to change the generated code.
 *
 *   ELECTRON_RUN_AS_NODE=1 Code.exe tools/test_gfx.js
 */

const crypto = require('crypto');
const cp = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const nvcache = require(path.join(ROOT, 'src', 'nvcache.js'));

const VK_COMPILE = path.join(ROOT, 'src', 'vk_compile.py');
const REFLECT = path.join(ROOT, 'src', 'spirv_reflect.py');
const ABI = path.join(ROOT, 'tools', 'vk_abi.json');
const FIXTURES = path.join(__dirname, 'fixtures', 'gfx');

let checks = 0;
let failures = 0;
let skipped = 0;

function check(condition, what, detail = '') {
  checks++;
  if (condition) return true;
  failures++;
  console.log(`  FAIL  ${what}`);
  if (detail) console.log(`        ${String(detail).split('\n').slice(0, 5).join('\n        ')}`);
  return false;
}

function skip(what) { skipped++; console.log(`  skip  ${what}`); }
function section(title) { console.log(`\n${title}`); }

function run(exe, args, env) {
  const r = cp.spawnSync(exe, args, {
    encoding: 'utf8', maxBuffer: 1 << 26,
    env: env ? { ...process.env, ...env } : process.env
  });
  return {
    code: r.status,
    stdout: (r.stdout || '').replace(/\r\n/g, '\n'),
    stderr: (r.stderr || '').replace(/\r\n/g, '\n'),
    spawnError: r.error
  };
}

/** The interpreter the extension would use, or null. */
function findPython() {
  for (const exe of process.platform === 'win32' ? ['py', 'python'] : ['python3', 'python']) {
    const r = run(exe, ['--version']);
    if (!r.spawnError && r.code === 0) return exe;
  }
  return null;
}

const PY = findPython();

// --------------------------------------------------------------------------- ABI

section('1. The Vulkan struct ABI');

if (!PY) {
  skip('no Python interpreter - the graphics lineage needs one, as the NVRTC backend does');
} else {
  // Not a style check. A field at the wrong offset makes the driver read a plausible value
  // from the wrong place, and the result is a shader compiled to the wrong thing rather than
  // an error - so ctypes' arithmetic is checked against what a C compiler computed from the
  // real headers. The frozen file is regenerated by `tools/vk_abi_freeze.py`.
  const report = run(PY, [VK_COMPILE, '--layout']);
  if (!check(report.code === 0, 'vk_compile.py reports its struct layout', report.stderr)) {
    // nothing to compare against
  } else if (!check(fs.existsSync(ABI), 'the frozen C layout is present', ABI)) {
    // nothing to compare against
  } else {
    const mine = JSON.parse(report.stdout);
    const frozen = JSON.parse(fs.readFileSync(ABI, 'utf8'));
    let mismatches = 0;
    let fields = 0;
    for (const name of Object.keys(frozen)) {
      const got = mine[name];
      if (!got) { mismatches++; console.log(`        missing from ctypes: ${name}`); continue; }
      if (got.sizeof !== frozen[name].sizeof) {
        mismatches++;
        console.log(`        ${name}: sizeof ctypes ${got.sizeof}, C ${frozen[name].sizeof}`);
      }
      for (const [field, offset] of Object.entries(frozen[name].fields)) {
        fields++;
        if (got.fields[field] !== offset) {
          mismatches++;
          console.log(`        ${name}.${field}: ctypes ${got.fields[field]}, C ${offset}`);
        }
      }
    }
    check(mismatches === 0,
      `every struct agrees with the C compiler ` +
      `(${Object.keys(frozen).length} structs, ${fields} fields)`,
      `${mismatches} mismatch(es)`);
    check(Object.keys(mine).length === Object.keys(frozen).length,
      'and neither side declares a struct the other does not',
      `ctypes ${Object.keys(mine).length}, frozen ${Object.keys(frozen).length}`);
  }
}

// --------------------------------------------------------------------------- reflection

section('2. SPIR-V reflection and producer synthesis');

const haveFixtures = fs.existsSync(path.join(FIXTURES, 'fsMain.spv'));

if (!PY) {
  skip('no Python interpreter');
} else if (!haveFixtures) {
  skip(`no SPIR-V fixtures under ${path.relative(ROOT, FIXTURES)}`);
} else {
  const reflected = run(PY, [REFLECT, path.join(FIXTURES, 'vsMain.spv'),
    path.join(FIXTURES, 'fsMain.spv'), '--json']);
  if (check(reflected.code === 0, 'the fixture pair reflects', reflected.stderr)) {
    const { layout } = JSON.parse(reflected.stdout);
    const tuples = layout.map(d => `${d.set}:${d.binding}:${d.type}:${d.count}`).join(' ');
    // The union of what the two stages declare: UBO 0, sampled image 1, sampler 2, SSBO 3.
    check(tuples === '0:0:6:1 0:1:2:1 0:2:0:1 0:3:7:1',
      'the merged layout is what the two stages actually declare', tuples);
  }

  // A layout no VkDescriptorSetLayout can express must be refused by name. Two descriptors at
  // one (set, binding) is the usual HLSL artefact - `t0` and `s0` collide without -fvk-s-shift.
  const collide = path.join(FIXTURES, 'collide.spv');
  if (fs.existsSync(collide)) {
    const r = run(PY, [REFLECT, collide, '--json']);
    check(r.code !== 0 && /declared twice/.test(r.stderr),
      'an inexpressible layout is refused rather than guessed at', r.stderr.split('\n')[0]);
  }
}

// --------------------------------------------------------------------------- round trip

section('3. The driver round-trip');

const KNOWN = {
  // A descriptor-free pair, and the same pair through the layout fixtures.
  plain: { vs: 'vs.spv', fs: 'fs.spv', layout: [], pixel: '6e77f0dbf9f6', vertex: '888a1deae26e' },
  bound: { vs: 'vsMain.spv', fs: 'fsMain.spv',
    layout: [[0, 0, 6, 1], [0, 1, 2, 1], [0, 2, 0, 1], [0, 3, 7, 1]],
    pixel: 'e2d27b236f6d', vertex: 'f64705929fad' }
};
const WRONG = { superset: '0a206c89ea37', dynamic: 'de06f203bf3b' };

async function pipeline(tag, request) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nvisa-gfx-'));
  const cache = path.join(dir, 'cache');
  fs.mkdirSync(cache);
  const file = path.join(dir, 'request.json');
  fs.writeFileSync(file, JSON.stringify(request), 'utf8');

  const r = run(PY, [VK_COMPILE, file], {
    __GL_SHADER_DISK_CACHE_PATH: cache,
    __GL_SHADER_DISK_CACHE: '1',
    __GL_SHADER_DISK_CACHE_SKIP_CLEANUP: '1'
  });
  if (r.code !== 0) {
    fs.rmSync(dir, { recursive: true, force: true });
    return { error: (r.stderr || r.stdout).trim().split('\n')[0], code: r.code };
  }

  const bin = findBin(cache);
  if (!bin) {
    fs.rmSync(dir, { recursive: true, force: true });
    return { error: 'the driver wrote nothing to the isolated cache' };
  }
  let toc = null;
  try { toc = fs.readFileSync(bin.slice(0, -4) + '.toc'); } catch (e) { toc = null; }
  const { objects } = await nvcache.enumerateObjects(fs.readFileSync(bin), {
    source: bin, backend: 'vk', toc, keepMicrocode: true, minCode: 0
  });
  const out = {};
  for (const o of objects) {
    const stage = (o.metadata && o.metadata.stage) || `code${o.metadata && o.metadata.stageCode}`;
    out[stage] = crypto.createHash('sha1').update(o.microcode).digest('hex').slice(0, 12);
  }
  fs.rmSync(dir, { recursive: true, force: true });
  return out;
}

function findBin(dir) {
  const stack = [dir];
  while (stack.length) {
    const at = stack.pop();
    for (const e of fs.readdirSync(at, { withFileTypes: true })) {
      const full = path.join(at, e.name);
      if (e.isDirectory()) stack.push(full);
      else if (e.name.endsWith('.bin')) return full;
    }
  }
  return null;
}

(async () => {
  const probe = PY ? run(PY, [VK_COMPILE, '--probe']) : null;

  if (!PY) {
    skip('no Python interpreter');
  } else if (!haveFixtures) {
    skip(`no SPIR-V fixtures under ${path.relative(ROOT, FIXTURES)}`);
  } else if (!probe || probe.code !== 0) {
    // No NVIDIA device, no Vulkan ICD, a Remote Desktop session: all real, none a defect here.
    skip(`no usable Vulkan device: ${(probe && (probe.stderr || probe.stdout) || '').trim().split('\n')[0]}`);
  } else {
    check(/vendor 0x10DE/i.test(probe.stdout), 'the probe names an NVIDIA device',
      probe.stdout.trim().split('\n').join(' | '));

    for (const [tag, want] of Object.entries(KNOWN)) {
      const got = await pipeline(tag, {
        vs: path.join(FIXTURES, want.vs),
        fs: path.join(FIXTURES, want.fs),
        layout: { bindings: want.layout }
      });
      if (!check(!got.error, `${tag}: the pipeline is created and the driver writes a cache`,
        got.error)) continue;
      check(got.pixel === want.pixel,
        `${tag}: the fragment microcode is what the C++ harness produced`,
        `got ${got.pixel}, want ${want.pixel}`);
      check(got.vertex === want.vertex,
        `${tag}: the vertex microcode is what the C++ harness produced`,
        `got ${got.vertex}, want ${want.vertex}`);
    }

    // The layout has to be load-bearing, or reproducing it proves nothing.
    const superset = await pipeline('superset', {
      vs: path.join(FIXTURES, 'vsMain.spv'), fs: path.join(FIXTURES, 'fsMain.spv'),
      layout: { bindings: [[0, 0, 6, 1], [0, 1, 2, 1], [0, 2, 0, 1], [0, 3, 7, 1],
        [0, 9, 6, 1], [0, 10, 7, 1], [0, 11, 2, 4]] }
    });
    check(!superset.error && superset.pixel === WRONG.superset,
      'a superset layout still produces the superset code, so the layout is load-bearing',
      superset.error || `got ${superset.pixel}, want ${WRONG.superset}`);

    // A mismatched producer/consumer pair is undefined, and the driver compiles it anyway.
    // Refusing is the only thing standing between that and a listing nobody can tell is wrong.
    const mismatched = await pipeline('mismatch', {
      vs: path.join(FIXTURES, 'vsMain.spv'), fs: path.join(FIXTURES, 'fs.spv'),
      layout: { bindings: [] }
    });
    check(!!mismatched.error && mismatched.code === 1,
      'a producer that does not match the consumer is refused before the driver sees it',
      mismatched.error || `it was accepted: ${JSON.stringify(mismatched)}`);
  }

  console.log(`\n${failures ? 'FAIL' : 'PASS'}  ${checks} checks, ${failures} failures, ` +
    `${skipped} skipped`);
  process.exit(failures ? 1 : 0);
})().catch(e => { console.log(`\nFAIL  ${e && e.stack ? e.stack : e}`); process.exit(1); });
